name: nexa
description: Controle financeiro pessoal simples e eficiente.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  fl_chart: ^1.1.1
  font_awesome_flutter: ^10.12.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1

  # Estado
  flutter_riverpod: ^3.3.1

  # Banco de dados
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4
  path: ^1.9.1

  # Formatação / Masks
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0

  # Notificações
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^5.0.2

  # Utilitários
  uuid: ^4.5.3
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#1A1A1A"
  image: "assets/images/nexa_icon.png"
  android_12:
    image: "assets/images/nexa_icon.png"
    color: "#1A1A1A"
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/nexa_icon.png"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/images/nexa_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
